apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - svc.yml
images:
- name: docker.io/vishamay/httpd
  newTag: "2.0"   # <-- ArgoCD Image Updater changes this automatically
